scrape_configs:
  - job_name: node-exporter
    scrape_interval: 5s
    static_configs:
      - targets:
          - node-exporter:9100

  - job_name: magi
    scrape_interval: 5s
    static_configs:
      - targets:
          - magi:9200

  - job_name: op-challenger
    scrape_interval: 5s
    static_configs:
      - targets:
          - op-challenger:9201
